### ISSUE TITLE
知网反爬

### ISSUE THREAD

**Issue by Topofme** [itstyren/CNKI-download#48]
知网改了网页源代码，讲搜索出来的div内容进行了隐藏，爬取的网页源代码中无检索的结果，报错：
Traceback (most recent call last):
  File "D:\code\CNKI-download-master (1)\CNKI-download-master\main.py", line 263, in <module>
    main()
  File "D:\code\CNKI-download-master (1)\CNKI-download-master\main.py", line 257, in main
    search.search_reference(get_uesr_inpt())
  File "D:\code\CNKI-download-master (1)\CNKI-download-master\main.py", line 100, in search_reference
    self.pre_parse_page(second_get_res.text), second_get_res.text)
  File "D:\code\CNKI-download-master (1)\CNKI-download-master\main.py", line 110, in pre_parse_page
    reference_num = re.search(reference_num_pattern_compile,
AttributeError: 'NoneType' object has no attribute 'group'
正则表达式无法检索到匹配项，返回None导致group()方法报错
知网更改了<div id="briefBox" style="display:none">
有没有人能在这个代码基础上读取到正确的标签的

**Comment by Chrisma-98** [comment]
> 这个地方稍微改改就能过了 正则中间的部分 替换乘 `r'找到(.*?)条结果'` 既可 不过后面的代码也不行了 知网彻底改了查询的结构 得重写才行了

大佬还有其他爬虫方案吗？

**Comment by czcxwe** [comment]
您好，邮件已经收到，会在两日内回复（如有必要）。感谢来信！

**Comment by gemingzhe** [comment]
知网返回为空,还有别的方案吗

**Comment by czcxwe** [comment]
您好，邮件已经收到，会在两日内回复（如有必要）。感谢来信！
